id: I25531429
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:17:33+00:00'
last_modified: '2022-06-08T11:54:39.370634+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4211
  title: ལོཙྪ་བ་ཆེན་པོ་རིན་ཆེན་བཟང་པོའི་རྣམ་ཐར་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E583:
      image_group_id: I1PD97317
      title: ''
      total_pages: 250
      order: 1
      base_file: E583.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
